# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Move' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Move
	pod 'Alamofire'
  pod 'SwiftMessages'
  target 'MoveTests' do
    inherit! :search_paths
 

    # Pods for testing
  end

  target 'MoveUITests' do
    # Pods for testing
  end

end
